In [16]:
import numpy as np
import pandas as pd

In [8]:
apl16 = np.loadtxt('AAPL-2016.csv',delimiter=",", dtype=str)
apl17 = np.loadtxt('AAPL-2017.csv',delimiter=",", dtype=str)

In [106]:
print(apl16)

[['Date' 'Open' 'High' ... 'Close' 'Adj Close' 'Volume']
 ['2016-01-04' '102.610001' '105.370003' ... '105.349998' '100.274513'
  '67649400']
 ['2016-01-05' '105.750000' '105.849998' ... '102.709999' '97.761681'
  '55791000']
 ...
 ['2016-12-23' '115.589996' '116.519997' ... '116.519997' '113.373917'
  '14249500']
 ['2016-12-27' '116.519997' '117.800003' ... '117.260002' '114.093948'
  '18296900']
 ['2016-12-28' '117.519997' '118.019997' ... '116.760002' '113.607445'
  '20905900']]


In [65]:
df_2016 = pd.read_csv('AAPL-2016.csv')
df_2016

Date        Open        High         Low       Close   Adj Close  \
0    2016-01-04  102.610001  105.370003  102.000000  105.349998  100.274513   
1    2016-01-05  105.750000  105.849998  102.410004  102.709999   97.761681   
2    2016-01-06  100.559998  102.370003   99.870003  100.699997   95.848511   
3    2016-01-07   98.680000  100.129997   96.430000   96.449997   91.803276   
4    2016-01-08   98.550003   99.110001   96.760002   96.959999   92.288696   
..          ...         ...         ...         ...         ...         ...   
245  2016-12-21  116.800003  117.400002  116.779999  117.059998  113.899338   
246  2016-12-22  116.349998  116.510002  115.639999  116.290001  113.150139   
247  2016-12-23  115.589996  116.519997  115.589996  116.519997  113.373917   
248  2016-12-27  116.519997  117.800003  116.489998  117.260002  114.093948   
249  2016-12-28  117.519997  118.019997  116.199997  116.760002  113.607445   

       Volume  
0    67649400  
1    55791000  
2    68457400  
3    81094400  
4    70798000  
..        ...  
245  23783200  
246  26085900  
247  14249500  
248  18296900  
249  20905900  

[250 rows x 7 columns]

In [103]:
df_2017 = pd.read_csv('AAPL-2017.csv')
df_2017

Date        Open        High         Low       Close   Adj Close  \
0    2017-01-03  115.800003  116.330002  114.760002  116.150002  113.013916   
1    2017-01-04  115.849998  116.510002  115.750000  116.019997  112.887413   
2    2017-01-05  115.919998  116.860001  115.809998  116.610001  113.461502   
3    2017-01-06  116.779999  118.160004  116.470001  117.910004  114.726402   
4    2017-01-09  117.949997  119.430000  117.940002  118.989998  115.777237   
..          ...         ...         ...         ...         ...         ...   
246  2017-12-22  174.679993  175.419998  174.500000  175.009995  173.023026   
247  2017-12-26  170.800003  171.470001  169.679993  170.570007  168.633423   
248  2017-12-27  170.100006  170.779999  169.710007  170.600006  168.663101   
249  2017-12-28  171.000000  171.850006  170.479996  171.080002  169.137650   
250  2017-12-29  170.520004  170.589996  169.220001  169.229996  167.308640   

       Volume  
0    28781900  
1    21118100  
2    22193600  
3    31751900  
4    33561900  
..        ...  
246  16114600  
247  33185500  
248  21498200  
249  16480200  
250  25884400  

[251 rows x 7 columns]

In [107]:
sliced_2016 = df_2016.iloc[0:50]
sliced_2016

Date        Open        High         Low       Close   Adj Close  \
0   2016-01-04  102.610001  105.370003  102.000000  105.349998  100.274513   
1   2016-01-05  105.750000  105.849998  102.410004  102.709999   97.761681   
2   2016-01-06  100.559998  102.370003   99.870003  100.699997   95.848511   
3   2016-01-07   98.680000  100.129997   96.430000   96.449997   91.803276   
4   2016-01-08   98.550003   99.110001   96.760002   96.959999   92.288696   
5   2016-01-11   98.970001   99.059998   97.339996   98.529999   93.783073   
6   2016-01-12  100.550003  100.690002   98.839996   99.959999   95.144165   
7   2016-01-13  100.320000  101.190002   97.300003   97.389999   92.697990   
8   2016-01-14   97.959999  100.480003   95.739998   99.519997   94.725372   
9   2016-01-15   96.199997   97.709999   95.360001   97.129997   92.450516   
10  2016-01-19   98.410004   98.650002   95.500000   96.660004   92.003166   
11  2016-01-20   95.099998   98.190002   93.419998   96.790001   92.126900   
12  2016-01-21   97.059998   97.879997   94.940002   96.300003   91.660500   
13  2016-01-22   98.629997  101.459999   98.370003  101.419998   96.533836   
14  2016-01-25  101.519997  101.529999   99.209999   99.440002   94.649239   
15  2016-01-26   99.930000  100.879997   98.070000   99.989998   95.172729   
16  2016-01-27   96.040001   96.629997   93.339996   93.419998   88.919250   
17  2016-01-28   93.790001   94.519997   92.389999   94.089996   89.556976   
18  2016-01-29   94.790001   97.339996   94.349998   97.339996   92.650391   
19  2016-02-01   96.470001   96.709999   95.400002   96.430000   91.784241   
20  2016-02-02   95.419998   96.040001   94.279999   94.480003   89.928192   
21  2016-02-03   95.000000   96.839996   94.080002   96.349998   91.708099   
22  2016-02-04   95.860001   97.330002   95.190002   96.599998   92.444969   
23  2016-02-05   96.519997   96.919998   93.690002   94.019997   89.975929   
24  2016-02-08   93.129997   95.699997   93.040001   95.010002   90.923355   
25  2016-02-09   94.290001   95.940002   93.930000   94.989998   90.904213   
26  2016-02-10   95.919998   96.349998   94.099998   94.269997   90.215187   
27  2016-02-11   93.790001   94.720001   92.589996   93.699997   89.669716   
28  2016-02-12   94.190002   94.500000   93.010002   93.989998   89.947243   
29  2016-02-16   95.019997   96.849998   94.610001   96.639999   92.483246   
30  2016-02-17   96.669998   98.209999   96.150002   98.120003   93.899597   
31  2016-02-18   98.839996   98.889999   96.089996   96.260002   92.119606   
32  2016-02-19   96.000000   96.760002   95.800003   96.040001   91.909050   
33  2016-02-22   96.309998   96.900002   95.919998   96.879997   92.712921   
34  2016-02-23   96.400002   96.500000   94.550003   94.690002   90.617134   
35  2016-02-24   93.980003   96.379997   93.320000   96.099998   91.966469   
36  2016-02-25   96.050003   96.760002   95.250000   96.760002   92.598099   
37  2016-02-26   97.199997   98.019997   96.580002   96.910004   92.741638   
38  2016-02-29   96.860001   98.230003   96.650002   96.690002   92.531113   
39  2016-03-01   97.650002  100.769997   97.419998  100.529999   96.205925   
40  2016-03-02  100.510002  100.889999   99.639999  100.750000   96.416466   
41  2016-03-03  100.580002  101.709999  100.449997  101.500000   97.134209   
42  2016-03-04  102.370003  103.750000  101.370003  103.010002   98.579269   
43  2016-03-07  102.389999  102.830002  100.959999  101.870003   97.488304   
44  2016-03-08  100.779999  101.760002  100.400002  101.029999   96.684410   
45  2016-03-09  101.309998  101.580002  100.269997  101.120003   96.770554   
46  2016-03-10  101.410004  102.239998  100.150002  101.169998   96.818390   
47  2016-03-11  102.239998  102.279999  101.500000  102.260002   97.861526   
48  2016-03-14  101.910004  102.910004  101.779999  102.519997   98.110329   
49  2016-03-15  103.959999  105.180000  103.849998  104.580002  100.081726   

       Volume  
0    67649400  

In [ ]:
sliced_2017 = df_2017.iloc[0:50]
sliced_2017

In [64]:
close_volume_2017 = np.array(sliced_2017[["Close", "Volume"]])
close_volume_2017

array([[1.16150002e+02, 2.87819000e+07],
       [1.16019997e+02, 2.11181000e+07],
       [1.16610001e+02, 2.21936000e+07],
       [1.17910004e+02, 3.17519000e+07],
       [1.18989998e+02, 3.35619000e+07],
       [1.19110001e+02, 2.44621000e+07],
       [1.19750000e+02, 2.75886000e+07],
       [1.19250000e+02, 2.70862000e+07],
       [1.19040001e+02, 2.61119000e+07],
       [1.20000000e+02, 3.44398000e+07],
       [1.19989998e+02, 2.37130000e+07],
       [1.19779999e+02, 2.55973000e+07],
       [1.20000000e+02, 3.25979000e+07],
       [1.20080002e+02, 2.20502000e+07],
       [1.19970001e+02, 2.32110000e+07],
       [1.21879997e+02, 3.23776000e+07],
       [1.21940002e+02, 2.63376000e+07],
       [1.21949997e+02, 2.05629000e+07],
       [1.21629997e+02, 3.03775000e+07],
       [1.21349998e+02, 4.92010000e+07],
       [1.28750000e+02, 1.11985000e+08],
       [1.28529999e+02, 3.37104000e+07],
       [1.29080002e+02, 2.45073000e+07],
       [1.30289993e+02, 2.68459000e+07],
       [1.315299

In [67]:
close_volume_2016 = np.array(sliced_2016[["Close", "Volume"]])
close_volume_2016

array([[1.05349998e+02, 6.76494000e+07],
       [1.02709999e+02, 5.57910000e+07],
       [1.00699997e+02, 6.84574000e+07],
       [9.64499970e+01, 8.10944000e+07],
       [9.69599990e+01, 7.07980000e+07],
       [9.85299990e+01, 4.97394000e+07],
       [9.99599990e+01, 4.91542000e+07],
       [9.73899990e+01, 6.24396000e+07],
       [9.95199970e+01, 6.31701000e+07],
       [9.71299970e+01, 7.90100000e+07],
       [9.66600040e+01, 5.30877000e+07],
       [9.67900010e+01, 7.23344000e+07],
       [9.63000030e+01, 5.21615000e+07],
       [1.01419998e+02, 6.58005000e+07],
       [9.94400020e+01, 5.17945000e+07],
       [9.99899980e+01, 7.50770000e+07],
       [9.34199980e+01, 1.33369700e+08],
       [9.40899960e+01, 5.56788000e+07],
       [9.73399960e+01, 6.44165000e+07],
       [9.64300000e+01, 4.09435000e+07],
       [9.44800030e+01, 3.73572000e+07],
       [9.63499980e+01, 4.59643000e+07],
       [9.65999980e+01, 4.64717000e+07],
       [9.40199970e+01, 4.64181000e+07],
       [9.501000

### Question 1

In [68]:
sum_2016 = close_volume_2016.sum(axis=1)
sum_2016

array([6.76495053e+07, 5.57911027e+07, 6.84575007e+07, 8.10944964e+07,
       7.07980970e+07, 4.97394985e+07, 4.91543000e+07, 6.24396974e+07,
       6.31701995e+07, 7.90100971e+07, 5.30877967e+07, 7.23344968e+07,
       5.21615963e+07, 6.58006014e+07, 5.17945994e+07, 7.50771000e+07,
       1.33369793e+08, 5.56788941e+07, 6.44165973e+07, 4.09435964e+07,
       3.73572945e+07, 4.59643963e+07, 4.64717966e+07, 4.64181940e+07,
       5.40214950e+07, 4.43312950e+07, 4.23436943e+07, 5.00747937e+07,
       4.03514940e+07, 4.90579966e+07, 4.48632981e+07, 3.90210963e+07,
       3.53742960e+07, 3.42808969e+07, 3.19426947e+07, 3.62557961e+07,
       2.75827968e+07, 2.89911969e+07, 3.52163967e+07, 5.04072005e+07,
       3.31697008e+07, 3.69558015e+07, 4.60552030e+07, 3.58290019e+07,
       3.15620010e+07, 2.72018011e+07, 3.35137012e+07, 2.74083023e+07,
       2.50762025e+07, 4.00678046e+07])

In [76]:
sum_2017 = close_volume_2017.sum(axis=1)
sum_2017

array([2.87820162e+07, 2.11182160e+07, 2.21937166e+07, 3.17520179e+07,
       3.35620190e+07, 2.44622191e+07, 2.75887198e+07, 2.70863192e+07,
       2.61120190e+07, 3.44399200e+07, 2.37131200e+07, 2.55974198e+07,
       3.25980200e+07, 2.20503201e+07, 2.32111200e+07, 3.23777219e+07,
       2.63377219e+07, 2.05630219e+07, 3.03776216e+07, 4.92011213e+07,
       1.11985129e+08, 3.37105285e+07, 2.45074291e+07, 2.68460303e+07,
       3.81839315e+07, 2.30042320e+07, 2.83500324e+07, 2.00656321e+07,
       2.30355333e+07, 3.32263350e+07, 3.56232355e+07, 2.25847354e+07,
       2.21983357e+07, 2.45073367e+07, 2.08370371e+07, 2.07883365e+07,
       2.17767367e+07, 2.02575369e+07, 2.34830370e+07, 3.64147398e+07,
       2.62111390e+07, 2.11082398e+07, 2.17501393e+07, 1.74464395e+07,
       1.87073390e+07, 2.21560387e+07, 1.96129391e+07, 1.74218392e+07,
       1.53092390e+07, 2.56919405e+07])

In [89]:
change_in_volume = close_volume_2017[:, 1] - close_volume_2016[:, 1]
change_in_volume

array([-3.886750e+07, -3.467290e+07, -4.626380e+07, -4.934250e+07,
       -3.723610e+07, -2.527730e+07, -2.156560e+07, -3.535340e+07,
       -3.705820e+07, -4.457020e+07, -2.937470e+07, -4.673710e+07,
       -1.956360e+07, -4.375030e+07, -2.858350e+07, -4.269940e+07,
       -1.070321e+08, -3.511590e+07, -3.403900e+07,  8.257500e+06,
        7.462780e+07, -1.225390e+07, -2.196440e+07, -1.957220e+07,
       -1.583760e+07, -2.132710e+07, -1.399370e+07, -3.000920e+07,
       -1.731600e+07, -1.583170e+07, -9.240100e+06, -1.643640e+07,
       -1.317600e+07, -9.773600e+06, -1.110570e+07, -1.546750e+07,
       -5.806100e+06, -8.733700e+06, -1.173340e+07, -1.399250e+07,
       -6.958600e+06, -1.584760e+07, -2.430510e+07, -1.838260e+07,
       -1.285470e+07, -5.045800e+06, -1.390080e+07, -9.986500e+06,
       -9.767000e+06, -1.437590e+07])

In [92]:
change_in_traded_volume = change_in_volume.sum(axis=0)
change_in_traded_volume

-1089213200.0

### Question 2

In [90]:
change = close_volume_2017 - close_volume_2016
change

array([[ 1.0800004e+01, -3.8867500e+07],
       [ 1.3309998e+01, -3.4672900e+07],
       [ 1.5910004e+01, -4.6263800e+07],
       [ 2.1460007e+01, -4.9342500e+07],
       [ 2.2029999e+01, -3.7236100e+07],
       [ 2.0580002e+01, -2.5277300e+07],
       [ 1.9790001e+01, -2.1565600e+07],
       [ 2.1860001e+01, -3.5353400e+07],
       [ 1.9520004e+01, -3.7058200e+07],
       [ 2.2870003e+01, -4.4570200e+07],
       [ 2.3329994e+01, -2.9374700e+07],
       [ 2.2989998e+01, -4.6737100e+07],
       [ 2.3699997e+01, -1.9563600e+07],
       [ 1.8660004e+01, -4.3750300e+07],
       [ 2.0529999e+01, -2.8583500e+07],
       [ 2.1889999e+01, -4.2699400e+07],
       [ 2.8520004e+01, -1.0703210e+08],
       [ 2.7860001e+01, -3.5115900e+07],
       [ 2.4290001e+01, -3.4039000e+07],
       [ 2.4919998e+01,  8.2575000e+06],
       [ 3.4269997e+01,  7.4627800e+07],
       [ 3.2180001e+01, -1.2253900e+07],
       [ 3.2480004e+01, -2.1964400e+07],
       [ 3.6269996e+01, -1.9572200e+07],
       [ 3.65199

In [88]:
sum_change = change.sum(axis=1)
sum_change

array([-3.88674892e+07, -3.46728867e+07, -4.62637841e+07, -4.93424785e+07,
       -3.72360780e+07, -2.52772794e+07, -2.15655802e+07, -3.53533781e+07,
       -3.70581805e+07, -4.45701771e+07, -2.93746767e+07, -4.67370770e+07,
       -1.95635763e+07, -4.37502813e+07, -2.85834795e+07, -4.26993781e+07,
       -1.07032071e+08, -3.51158721e+07, -3.40389757e+07,  8.25752492e+06,
        7.46278343e+07, -1.22538678e+07, -2.19643675e+07, -1.95721637e+07,
       -1.58375635e+07, -2.13270630e+07, -1.39936618e+07, -3.00091616e+07,
       -1.73159607e+07, -1.58316616e+07, -9.24006261e+06, -1.64363609e+07,
       -1.31759603e+07, -9.77356018e+06, -1.11056576e+07, -1.54674596e+07,
       -5.80606010e+06, -8.73365998e+06, -1.17333597e+07, -1.39924607e+07,
       -6.95856179e+06, -1.58475617e+07, -2.43050637e+07, -1.83825623e+07,
       -1.28546620e+07, -5.04576244e+06, -1.39007620e+07, -9.98646306e+06,
       -9.76696353e+06, -1.43758641e+07])

In [95]:
sum_change_volume = sum_change.sum(axis=0)
sum_change_volume

-1089211640.5900083

### Question 3

In [101]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})
# np.set_printoptions()

print(change)

[[ 10.80 -38867500.00]
 [ 13.31 -34672900.00]
 [ 15.91 -46263800.00]
 [ 21.46 -49342500.00]
 [ 22.03 -37236100.00]
 [ 20.58 -25277300.00]
 [ 19.79 -21565600.00]
 [ 21.86 -35353400.00]
 [ 19.52 -37058200.00]
 [ 22.87 -44570200.00]
 [ 23.33 -29374700.00]
 [ 22.99 -46737100.00]
 [ 23.70 -19563600.00]
 [ 18.66 -43750300.00]
 [ 20.53 -28583500.00]
 [ 21.89 -42699400.00]
 [ 28.52 -107032100.00]
 [ 27.86 -35115900.00]
 [ 24.29 -34039000.00]
 [ 24.92  8257500.00]
 [ 34.27  74627800.00]
 [ 32.18 -12253900.00]
 [ 32.48 -21964400.00]
 [ 36.27 -19572200.00]
 [ 36.52 -15837600.00]
 [ 37.05 -21327100.00]
 [ 38.15 -13993700.00]
 [ 38.42 -30009200.00]
 [ 39.30 -17316000.00]
 [ 38.38 -15831700.00]
 [ 37.39 -9240100.00]
 [ 39.09 -16436400.00]
 [ 39.68 -13176000.00]
 [ 39.82 -9773600.00]
 [ 42.42 -11105700.00]
 [ 40.43 -15467500.00]
 [ 39.90 -5806100.00]
 [ 40.02 -8733700.00]
 [ 40.30 -11733400.00]
 [ 39.26 -13992500.00]
 [ 38.21 -6958600.00]
 [ 38.28 -15847600.00]
 [ 36.33 -24305100.00]
 [ 37.65 -183826

### Question 4

In [105]:
combined_years = np.concatenate( (np.array(sliced_2016), np.array(sliced_2017)), axis=0 )

combined_years



array([['2016-01-04', 102.610001, 105.370003, 102.0, 105.349998,
        100.274513, 67649400],
       ['2016-01-05', 105.75, 105.849998, 102.410004, 102.709999,
        97.761681, 55791000],
       ['2016-01-06', 100.559998, 102.370003, 99.870003, 100.699997,
        95.848511, 68457400],
       ['2016-01-07', 98.68, 100.129997, 96.43, 96.449997, 91.803276,
        81094400],
       ['2016-01-08', 98.550003, 99.110001, 96.760002, 96.959999,
        92.288696, 70798000],
       ['2016-01-11', 98.970001, 99.059998, 97.339996, 98.529999,
        93.783073, 49739400],
       ['2016-01-12', 100.550003, 100.690002, 98.839996, 99.959999,
        95.144165, 49154200],
       ['2016-01-13', 100.32, 101.190002, 97.300003, 97.389999, 92.69799,
        62439600],
       ['2016-01-14', 97.959999, 100.480003, 95.739998, 99.519997,
        94.725372, 63170100],
       ['2016-01-15', 96.199997, 97.709999, 95.360001, 97.129997,
        92.450516, 79010000],
       ['2016-01-19', 98.410004, 98.650002, 